export const newsFlashStyles = {
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    zIndex: 999, // Lower z-index so it doesn't block everything
    paddingTop: 80,
  },
  newsContainer: {
    backgroundColor: '#1a1a2e',
    borderRadius: 16,
    marginHorizontal: 20,
    borderLeftWidth: 4,
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    maxWidth: '90%',
    width: '90%',
  },
  newsContent: {
    padding: 20,
  },
  newsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  newsIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  breakingText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#4facfe',
    letterSpacing: 1.2,
  },
  closeButton: {
    padding: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  sentimentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  sentimentText: {
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  newsText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    lineHeight: 24,
    marginBottom: 16,
    textAlign: 'center',
  },
  questionText: {
    fontSize: 14,
    color: '#8e8e93',
    textAlign: 'center',
    marginBottom: 16,
    fontStyle: 'italic',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    gap: 4,
  },
  buyButton: {
    backgroundColor: '#38ef7d',
  },
  sellButton: {
    backgroundColor: '#ff6b6b',
  },
  dismissButton: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(142, 142, 147, 0.3)',
  },
  buttonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  dismissButtonText: {
    color: '#8e8e93',
    fontSize: 14,
    fontWeight: '600',
  },
  modeInfo: {
    backgroundColor: 'rgba(79, 172, 254, 0.1)',
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(79, 172, 254, 0.2)',
  },
  modeInfoText: {
    fontSize: 11,
    color: '#4facfe',
    textAlign: 'center',
    fontWeight: '500',
  },
  timerContainer: {
    alignItems: 'center',
    marginTop: 8,
  },
  timerText: {
    fontSize: 10,
    color: '#8e8e93',
    fontStyle: 'italic',
  },
};
